module.exports = {
    'schoolParts': [
        {name:'小学',kemus:[
            {id:19,name:"语文"},
            {id:20,name:"数学"},
            {id:21,name:"英语"},
            ],
            term:[
                {id:0,name:"不限"},
                {id:1,name:"一年级上册"},
                {id:2,name:"一年级下册"},
                {id:3,name:"二年级上册"},
                {id:4,name:"二年级下册"},
                {id:5,name:"三年级上册"},
                {id:6,name:"三年级下册"},
                {id:7,name:"四年级上册"},
                {id:8,name:"四年级下册"},
                {id:9,name:"五年级上册"},
                {id:10,name:"五年级下册"},
                {id:11,name:"六年级上册"},
                {id:12,name:"六年级下册"},
            ]},            
        {name:'初中',kemus:[
            {id:1,name:"语文"},
            {id:2,name:"数学"},
            {id:3,name:"英语"},
            {id:4,name:"物理"},
            {id:5,name:"化学"},
            {id:6,name:"历史"},
            {id:7,name:"地理"},
            {id:8,name:"生物"},
            {id:9,name:"政治"},
            ],
            term:[
                {id:0,name:"不限"},
                {id:13,name:"七年级上册"},
                {id:14,name:"七年级下册"},
                {id:15,name:"八年级上册"},
                {id:16,name:"八年级下册"},
                {id:17,name:"九年级上册"},
                {id:18,name:"九年级下册"},
            ]}
        ],
  }